### ISSUE TITLE
Only android, right?

### ISSUE THREAD

**Issue by adrienthiery** [theanam/react-native-docker#3]
Hey there,

More of a question, than an issue.

Logically, this allows you only to run a react-native app for Android, right ?

**Comment by theanam** [comment]
Sorry My email preference was weird, and didn't notice. 
This basically lets you build React native apps in a container.  If you don't want to install and configure all the dependencies yourself or if you are building the app in a CI/CD environment.

**Comment by theanam** [comment]
Closing this issue. Long story short: Only android can be built right now because there's no OSX base image available (that I know of)
