### ISSUE TITLE
[Doubt] Deploy from docker container to host emulator/device

### ISSUE THREAD

**Issue by cirovargas** [theanam/react-native-docker#8]
Hi,

You did the deploy of react-native run-android to emulator in the host of container?

Inside the container when i prompt 'adb devices' no one device is listed

**Comment by theanam** [comment]
in order to use adb to detect your devices, you need to give your container access to your USB devices.

here's a thread that will help: https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device
